#!/bin/bash

battery=$(cat /sys/class/power_supply/BAT0/capacity)
charging=$(cat /sys/class/power_supply/BAT0/status)
temp_notify="/tmp/dwmblocks-battery-notification"
temp_full="/tmp/dwmblocks-battery-full"

if [ $charging = "Charging" ]; then
    if ! [[ -f $temp_notify ]]; then
        touch $temp_notify
        echo -e "SEC:1\tTAG:battery\tCharging ⚡" > $XNOTIFY_FIFO
    fi
    if ! [[ -f $temp_full ]]; then
        touch $temp_full
    fi
    printf "%s⚡" $battery

elif [ $charging = "Full" ]; then
    if [[ -f $temp_full ]]; then
        rm $temp_full
        echo -e "SEC:3\tTAG:battery\tFully charged⚡" > $XNOTIFY_FIFO
    fi
    printf "%s🔋" $battery

elif (( $battery > 10 )); then
    if ! [[ -f $temp_notify ]]; then
        touch $temp_notify
        echo -e "SEC:1\tTAG:battery\tDischarging ⚡" > $XNOTIFY_FIFO
    fi
    printf "%s🔋" $battery
else
    if [[ -f $temp_notify ]]; then
        rm $temp_notify
        echo -e "TAG:battery\tLow battery🪫" > $XNOTIFY_FIFO
    fi
    printf "%s🪫" $battery
fi
