#!/bin/sh

vol=$(pulseaudio-ctl full-status | cut -d" " -f1)
mute=$(pulseaudio-ctl full-status | cut -d" " -f2)

if [ "$mute" == "yes" ]; then
    printf "%s🔇" $vol

else
    printf "%s🔈" $vol
fi

#pkill -RTMIN+5 dwmblocks
