#!/bin/bash

# Open multiple tabs with different search engines for searching a term

prompt=$QUTE_SELECTED_TEXT

# Search engines to open
declare -a engines_list=("arxiv" "scholar" "g")

# Create the qtb command
command=""

for curr_engine in "${engines_list[@]}"
do
    command="${command} open -t ${curr_engine} $prompt;;"
done

command="${command} message-info 'Multiples seaches of $prompt'"

# Return command
echo "$command" >> "$QUTE_FIFO"
